### ISSUE TITLE
Migrate eBMS transect input system to latest eBMS checklist

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#108]
links to #98 and #47 

Harmonise checklists 254 and 251.  

Switch the eBMS transect input system to using list 251

**Comment by johnvanbreda** [comment]
@Gary-van-Breda any objections to switching to list 251 for the transect data entry? I think this part may need to be done by you so you can check the implications e.g. on the sub-lists used by the transect system.
I'll write a query for moving the existing records over to list 251.

**Comment by DavidRoy** [comment]
We also need to move to list 251 to gain the benefit of having the country-coding, i.e. for each species a list of countries in which present

**Comment by johnvanbreda** [comment]
Before the migration, I double checked there are simple mappings between the 2 lists. If I run the following query I get a list of taxa from list 254 which don't have an exact name match in 251:
```sql
select distinct cttl1.id, cttl1.taxon
from occurrences o
join cache_taxa_taxon_lists cttl1 on cttl1.id=o.taxa_taxon_list_id and cttl1.taxon_list_id=254
left join cache_taxa_taxon_lists cttl2 on cttl2.taxon=cttl1.taxon and cttl2.taxon_list_id=251
where o.website_id=118
and cttl2.id is null
```
The list is
```
432867	"Carcharodus flocciferus"
433064	"Aricia eumedon"
433085	"Polyommatus bellargus"
433086	"Polyommatus coridon"
433111	"Argynnis aglaja"
433112	"Argynnis adippe"
433113	"Argynnis niobe"
433250	"Erebia alberganus"
433345	"White sp."
433348	"Wood White/Real's Wood White"
433350	"Skipper sp."
433351	"Pieris sp."
433356	"Thymelicus sp."
433999	"Polyommatus sp."
434017	"Colias hyale\alfacariensis\croceus"
434018	"Polyommatus icarus\thersites"
434021	"Leptidea sinapis\juvernica\reali"
434023	"Thymelicus lineolus\sylvestris"
```

Once we have the mappings sorted, the query following (with a modification for the mappings) will find a list of occurrence IDs with old taxa_taxon_list_ids and proposed new ones:
```sql
select o.id, cttl1.id as old_taxa_taxon_list_id, cttl2.id as new_taxa_taxon_list_id, cttl1.taxon
from occurrences o
join cache_taxa_taxon_lists cttl1 on cttl1.id=o.taxa_taxon_list_id and cttl1.taxon_list_id=254
join cache_taxa_taxon_lists cttl2 on cttl2.taxon=cttl1.taxon and cttl2.taxon_list_id=251
where o.website_id=118;
```

After running that, we'll want to put something into the work_queue to make sure the cache tables are updated.

**Comment by DavidRoy** [comment]
here are the mappings:


id | taxon | action
-- | -- | --
432867 | Carcharodus flocciferus | to add
433064 | Aricia eumedon | synonym of Eumedonia eumedon
433085 | Polyommatus bellargus | synonym of Lysandra bellargus
433086 | Polyommatus coridon | synonym of Lysandra coridon
433111 | Argynnis aglaja | synonym of Speyeria aglaja
433112 | Argynnis adippe | synonym of Fabriciana adippe
433113 | Argynnis niobe | synonym of Fabriciana niobe
433250 | Erebia alberganus | to add
433345 | White sp. | to add (English name for Pieris sp.)
433348 | Wood White/Real's Wood White | to add (English name for Leptidea sinapis/juvernica)
433350 | Skipper sp. | to add
433351 | Pieris sp. | to add
433356 | Thymelicus sp. | to add
433999 | Polyommatus sp. | to add
434017 | Colias hyale\alfacariensis\croceus | to add
434018 | Polyommatus icarus\thersites | to add
434021 | Leptidea sinapis\juvernica\reali | to add
434023 | Thymelicus lineolus\sylvestris | to add

**Comment by Gary-van-Breda** [comment]
At the moment the main walk data entry page is using 254 - is there a particular time we want to switch it over to using 251?

**Comment by DavidRoy** [comment]
Switch as soon as possible.  The site can be put into maintenance mode if necessary.

**Comment by Gary-van-Breda** [comment]
Pages which reference List 254:
Walk data entry: node 36
Timed count data entry: node 39
Annual Report: node 43
Mapping: node 44
Year index plot: node 45
Section plot: node 46

Pages that already reference list 251:
Explore my records: node 59
Edit an app record: node 63

@johnvanbreda : are we going to change all the TTL ids on the existing occurrences to point to their equivalents on 251? If so it makes sense for us to do in the following order:

- Swap data entry pages to new list
- Update occurrences
- Rebuild caches (including rebuild of summary_builder output)
- Update data output pages.

Thoughts?

**Comment by DavidRoy** [comment]
My view is that we retain the 'old' 254 list but the 'new' 251 list becomes the preferred list - for all reporting and for data capture going forward.  I 'think' this means retaining the old taxon list and not changing the occurrences.  The work is then to use taxon_meaning to link the two lists together?

So the order becomes:
- Swap data entry pages to new list
- Update taxon_lists
- Rebuild caches (including rebuild of summary_builder output)
- Update data output pages

thanks
David

**Comment by johnvanbreda** [comment]
Using the external key and search code to link the lists should work and is easier than the taxon_meaning_id.

**Comment by DavidRoy** [comment]
@johnvanbreda can you do the list linking in that case, plus rebuild the cache.

@Gary-van-Breda to swap data entry and reporting pages (which will remain unaffected in the meantime as the 'old' list still exists?)

**Comment by Gary-van-Breda** [comment]
Following pages switched to "Able butterflies" species list, id 251
Walk data entry: node 36
Timed count data entry: node 39
Annual Report: node 43
Mapping: node 44
Year index plot: node 45
Section plot: node 46

**Comment by johnvanbreda** [comment]
@DavidRoy I'm working on the list linking and have the following questions:
1. For any taxa I need to add to list 251 as described in the comment above, is it OK if I sequentially allocate a new taxon version key using the same pattern ('eBMS...') used so far?
2. Carcharodus flocciferus (Tufted Marbled Skipper) is down as Carcharodus floccifera in list 252 already. It's not clear which is correct even after Googling - both are used. 
3. Where your lookup table of links between the 2 lists above describes a name as a synonym of something, do you want that synonym to be copied into list 251, or me to just create a link from the name in list 254 to the preferred name in list 251? The consequence of the just linking is that Elasticsearch will think the name was recorded as the preferred name, not the synonym, so maybe we should copy the synonyms over?
4. Erebia alberganus is Erebia albergana in list 251. Please confirm which is correct.
5. Should we really be adding versions of genus names with " sp." added at the end?

**Comment by DavidRoy** [comment]
@johnvanbreda.  Thanks for checking these.  We are aligning to the latest European checklist (https://zookeys.pensoft.net/article/28712/list/5/), so in answer

1. Yes
2. Carcharodus floccifera is the current preferred name.  Carcharodus flocciferus should be a synonym of this.
3. yes, copy the synonym over.  Linking to the preferred name.
4. Erebia albergana is the current preferred name.  Erebia alberganus should be a synonym of this
5. Agreed.  Remove 'sp.' from Genus level recording aggregates

**Comment by johnvanbreda** [comment]
Thanks. I've done the mapping from list 254 to 251 now and this means that the prototype of the Explore page now shows species names: https://butterfly-monitoring.net/elastic/my-records.

@Gary-van-Breda is there anything needed related to rebuilding the summary occurrences?

**Comment by DavidRoy** [comment]
When logged in under my email, not all records have common names showing via ES explore report - https://butterfly-monitoring.net/elastic/my-records

**Comment by DavidRoy** [comment]
Examples screenshot of https://butterfly-monitoring.net/elastic/my-records when masquarading as user = https://butterfly-monitoring.net/user/3/edit

Delay in rebuilding the index?

![es report](https://user-images.githubusercontent.com/2699478/62042585-59e8a200-b1f6-11e9-9c04-89b918dda235.png)

**Comment by johnvanbreda** [comment]
There were issues picking up some taxa from list 254 for use in ES. Should resolve itself this evening when the Work Queue finishes processing as a result of moving over to list 251 (see 113).

**Comment by Gary-van-Breda** [comment]
I have reset the summariser and set it into catch up mode for Survey ID 562,
I'll leave it run overnight, and check the Annual summary and Year plot data tomorrow.
(see #113 )

**Comment by DavidRoy** [comment]
https://butterfly-monitoring.net/elastic/my-records  now showing name for all records.  

Annual summary pages still not displaying expected data

**Comment by Gary-van-Breda** [comment]
Annual Summary is still catching up.
Data populated for 2016 (first EBMS data date) through to 2018 so far.

**Comment by johnvanbreda** [comment]
As noted elsewhere, expect additional delays in cache table updates due to large iNaturalist catch up since yesterday.

**Comment by DavidRoy** [comment]
Closing as lists updated
