### ISSUE TITLE
Improved overview map for eBMS

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#123]
The map at https://butterfly-monitoring.net/mydata needs improving in the following ways.
1. correct the issue with a data point off the coast of Africa (0,0 lat,lon?)
2. map of Europe showing eBMS data, with different symbols for surveys (562 and 565) as follows:
- points for survey = 562 should be coloured blue and labelled 'eBMS Transects'
- points for survey = 565 should be coloured red and labelled 'eBMS Timed counts'

Use ElasticSearch for map

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I'll pick this up now.

**Comment by johnvanbreda** [comment]
@DavidRoy this is now on the test site. Shall I deploy it to live? I'm not sure about the question regarding missing transects from Cris above though.

**Comment by DavidRoy** [comment]
@johnvanbreda tried https://test-butterfly-monitoring.pantheonsite.io/mydata and get an error message:
Elasticsearch query failed

**Comment by johnvanbreda** [comment]
I've fixed the permissions issue. Waiting for @Gary-van-Breda to confirm it is OK to push through all pending code changes to live.

**Comment by Gary-van-Breda** [comment]
Yes: please do.

**Comment by johnvanbreda** [comment]
Thanks - done.

**Comment by CrisSevilleja** [comment]
@Gary-van-Breda @DavidRoy 
I realised that the map of Europe in My Data https://butterfly-monitoring.net/mydata is labelled wrong. 

It should be the opposite:
points for survey = 562 should be coloured blue and labelled 'eBMS Timed counts'
points for survey = 565 should be coloured red and labelled 'eBMS Transects'

In the selection tab for samples and maps, the labels are shown wrong

**Comment by DavidRoy** [comment]
Well spotted!

@johnvanbreda  can you fix.  This error is in the map legend/selector not the page text

**Comment by johnvanbreda** [comment]
Fixed

**Comment by DavidRoy** [comment]
sorry John, not fixed.   It is the map controls that need changing

The labels need to be switched around.  There are no eBMS transects in the UK

**Comment by johnvanbreda** [comment]
Sorry, I'm not up to speed with what the app is doing but I think the request above is wrong.
According to the warehouse:
562 = EBMS Live, this survey has a parent/child structure in the hierarchy so must be the transects
565 = EBMS Mobile App, this survey has no parent samples so I assume is timed counts.

Given that, I've reverted to the original request:
* points for survey = 562 should be coloured blue and labelled 'eBMS Transects'
* points for survey = 565 should be coloured red and labelled 'eBMS Timed counts'
