### ISSUE TITLE
users unable to register on dev

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#124]
There is a bug in the registration process, the page asks for "Scheme you are part of" and that list is NULL because the dropdown is empty.

Also, the registration has two dropdowns:
Scheme you are part of (mandatory)
Country/scheme you are part of (optional)

Action required.
1. populate list of schemes for drop-down
2. remove country/scheme dropdown as now superfluous

**Comment by Gary-van-Breda** [comment]
Done.

**Comment by Gary-van-Breda** [comment]
I have also synchronised Test with Live

**Comment by DavidRoy** [comment]
List now appears but login/registration still not possible.

When trying to register, get this error - The email davidroy.cyprus.bms@gmail.com is reserved, and cannot be used.
![able login 2](https://user-images.githubusercontent.com/2699478/64125136-e3b0ff80-cda0-11e9-8bf2-ffd523ec3d41.png)

When trying to get password reset for this email, get this error - Error message
davidroy.cyprus.bms@gmail.com is not recognized as a username or an email address.
![able login 1](https://user-images.githubusercontent.com/2699478/64125155-03482800-cda1-11e9-92c5-1c7f25bd028b.png)

Both cannot be true?

**Comment by Gary-van-Breda** [comment]
I've set the "User restriction" mask for "Two dots email address with dot com" on Dev to match the corrected one on Live: this was preventing this particular email address from being used, in the first instance as a email address for the user, so the user was not created, when then meant logging in with that user/email failed.

**Comment by DavidRoy** [comment]
Thanks.  Closing as now resolved
