### ISSUE TITLE
Issue: transect display without sections

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#413]
### Describe the issue

There is a bug in the transects display. In the part where we can select the transect, only the first transects appear normally, the followings appear with 0 sections and it is not possible to select them and visualize the sections (see the attached screenshots). Unfortunately, this issue is still occurring on their smartphones and for some of Luxembourg's transects. 

I checked some of these transects on the website and they appear well, several sections and drawn on the website. 

### Expected behavior

I would expect to see all the transects associated with an account, displaying the number of sections and the map correctly when selecting the transect. Also, being able to select every transect to collect data.

### To Reproduce

1. Go to eBMS Transect
2. Select Sections to select the registered transect
3. Select the transect to survey and correspoding sections

### App Version

1.  They didn't provide me the version

### When did this happen

since last summer, 2021

### Screenshots

![transect display error LUX2](https://user-images.githubusercontent.com/25052478/164430833-a983e031-ea0b-432a-ae48-fd31a5e425a2.png)
![transect display error LUX](https://user-images.githubusercontent.com/25052478/164430837-c7981641-21ab-4bb7-ad00-d47baf633d9d.png)

**Comment by kazlauskis** [comment]
Thanks for reporting this, we'll have a look.

**Comment by CrisSevilleja** [comment]
Some more information: 
"We have this problem on all our devices: Android (BlackView, Samsung…, with the version v1.15.0 (87)) and iPhone (v1.15(90)). Yes, we noticed the problem around June 2021. Everyone that has at least 7 transects has the problem.

I join two screenshots to explain you the problem:
“7_transects”: here I have 7 transects allocated to me. The 6 first transects appear normally, but the 7th has already a problem (it shows 5 sections instead of 16).
“10_transects”: here I allocated to me 3 more transects, so 10 in total. Again we see that the 6 first appear normally, the 7th appear with 6 sections instead of 16, and the followings appear with 0 section.

Regardless of the transect, it is the order in which it appears in the list that matters. For example on “7_transects”, Kiemerchen appears normally because it is at the 5th position. But on “10_transects”, it appears with 0 section because it is at the 8th position. It is as if there was a maximum number of transects (or rather sections?) that could be displayed. When this maximum is exceeded, no more sections are displayed."

![7_transects](https://user-images.githubusercontent.com/25052478/164721609-949c7ade-22d4-4780-9849-784de440a902.jpg)
![10_transects](https://user-images.githubusercontent.com/25052478/164721633-03ea526c-3c50-4683-b6a8-b871014850a9.jpg)

I think there is an issue with the maximum number of transect displayed. Thanks for looking at this.

**Comment by kazlauskis** [comment]
This is fixed now and will be available in v1.16.0.

The reason for this issue was a default maximum of total 100 sections returned by the report. We have now increased this to 3000.

**Comment by SarahVray** [comment]
Dear @kazlauskis and @CrisSevilleja, it seems this issue came back with the new version of the App (v1.26.2 on both Android and Apple). Some transects appear again with 0 section :-(

**Comment by kazlauskis** [comment]
@SarahVray can you provide the user name or their ID and the transects that are affected?

**Comment by SarahVray** [comment]
@kazlauskis we are several to have the problem, here are some examples:
For me ("sarahvray (171)") on Android: 3 transects with 0 section and 1 with only 4 sections (instead of 16):
![Screenshot_20240529-154045](https://github.com/BiologicalRecordsCentre/ABLE/assets/110041178/cf093aca-c9c7-41bd-be02-9e5829b68c75)
For "Youri (2465)" on iPhone:
![Screenshot_20240529-154514](https://github.com/BiologicalRecordsCentre/ABLE/assets/110041178/afb010e0-4d22-4e63-b8dc-bb237201646c)
For "Lionel L'Hoste (37)" on Android:
![Screenshot_20240529-154352](https://github.com/BiologicalRecordsCentre/ABLE/assets/110041178/aeb89c5e-e64f-4a77-8d36-922bc082addb)

Thanks!

**Comment by kazlauskis** [comment]
@SarahVray Thanks again for reporting this. This issue affects users with over 100 sections across all transects, I have increased the limit now. The new version, 1.26.3, with the fix will come out shortly.

**Comment by SarahVray** [comment]
@kazlauskis Great thank you :-)
