### ISSUE TITLE
Urgent: Warning message entering Transect data - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#434]
A new warning message appears when entering new records on the Walk Entry Data.
_The following warnings have been identified
The value entered for this taxon on this transect section (1) exceeds
the expected maximum (undefined)
The total seen for this taxon on this walk (1) exceeds the expected
maximum (undefined)
Do you still wish to enter this data?_

This new warning message is annoying, it is appearing for every included record without any distinction, if it is a new species or based on species distribution data. Is this related to the verification system? 

Please @Gary-van-Breda remove this warning message for every record, if you want it can appear but just once at the end of entering all the data. And if possible to translate that message, people are quite confused. 

We are in the middle of the season and a lot of people are submitting data. Thanks
@DavidRoy

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : Fix deployed to Live.

**Comment by CrisSevilleja** [comment]
@Gary-van-Breda thank you for working on this but I still get the warning message for every record type on the Walk Entry Data https://butterfly-monitoring.net/walk-data-entry?sample_id=18585178 
@DavidRoy did you want this warning message to appear for every record?

**Comment by DavidRoy** [comment]
@CrisSevilleja can you send a screenshot of the message.  Is it the copyright statement at the bottom of the page?

**Comment by CrisSevilleja** [comment]
@DavidRoy  this is the warning message appearing every time you enter a record 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/25052478/172067319-08b5da80-ed21-4ddd-a1ea-a16294e18247.png">

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : I've masqueraded in as you, and I am not seeing the probelm. Can you clear your browser caches and try again?

**Comment by CrisSevilleja** [comment]
Hi @Gary-van-Breda now I tried in Chrome and Edge and the warning message doesn't appear anymore. Thank you for that!

the only thing now is a new message 'Mandatory Section Data. You must enter the highlighted section related data before you may enter any species counts". That is okay, you just need to close it. But every time I enter in a new visit or in a former visit, the %Sun is not saved and this message appears. I think there are problems to save the %sun/Cloud

Also, when you have entered some records entering a second time, the web doesn't allow you to edit the records. Below on the screenshot in darker grey records entered before without the possibility to edit. I tried in both browsers Chrome and Edge and it doesn't work
![image](https://user-images.githubusercontent.com/25052478/172187599-d94f6489-90c2-4566-b313-b90b75aa1f4f.png)

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : can you tell me what the walk sample ID is for the above?

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : I have deployed a fix to the initial validation, so this should now work when you try to edit existing data - the form is now meant to force the mandatory sun/cloud and reliability to be filled in before any species attributes.

**Comment by CrisSevilleja** [comment]
@Gary-van-Breda  the walk sample ID I used as an example https://butterfly-monitoring.net/walk-data-entry?sample_id=18632172
I checked this issue now and you were right, there was a problem saving the sun/cloud and reliability numbers. Now those variables can be saved, so it is possible to edit the records. 

Thank you so much
