### ISSUE TITLE
15 min counts on website: able to change butterfly names, but NOT dragonfly or bumblebee names

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#584]
@DavidRoy @JimBacon 
A recorder informed me that he could change speciesnames from butterflies in a 15min counts on the website, but NOT from bumblebees and dragonflies. Just gave it a try myself and made a fake 15min count with a butterfly and a dragonfly (ID 30798676 and 30798675). I could change the butterfly from 'klein koolwitje' to 'klein geaderd witje', but could NOT change the dragonfly from 'weidebeekjuffer' to 'bosbeekjuffer'. 

Of course recorders should not make mistakes, but it happens to all of us and you should be able to correct it, also on the website after uploading.

And as bonus question: how do I remove a (fake) visit? Realise now I probably should have put the app in training mode, but forgot that. 

And anyway every recorder should be able to delete his own counts and records. However when I go to the My data on the webpage www.butterfly-monitoring.net, I don't see something like 'My 15 min counts' or so. @DavidRoy @CrisSevilleja  is there a reason why you don't show this? I do see My mothcounts and My transects (which I don't have, at least not in this system).

**Comment by JimBacon** [comment]
This issue sounds like the second part of [an existing one](https://github.com/BiologicalRecordsCentre/ABLE/issues/457#issuecomment-1180620478)

With regard to the bonus question, under My Data there is 

- My Transects: a calendar view of butterfly transects
- My Samples: a list of butterfly, 15-minute, and moth trap samples.
- My Moth Trap Samples: a calendar view of moth trapping

You can edit and then delete 15-minute counts from the My Samples page.

It seems you already succeeded in deleting the [test 15-minute count](https://butterfly-monitoring.net/mydata/samples/edit?sample_id=22340025) you created.

**Comment by chrisvanswaay** [comment]
Thanks @JimBacon . Still the problem of the dragonfly and bumblebeenames has to be solved, this generates errors in the dataset.

**Comment by CrisSevilleja** [comment]
This is important to give priority @DavidRoy , at the moment, any error will remain because of the inability to edit

**Comment by JimBacon** [comment]
I have deployed a solution for this issue which involves having a separate recording grid for each species group. This has the added advantage of showing only the appropriate stage attribute for the species group.

@chrisvanswaay, would you like to test and close the issue if okay.

**Comment by chrisvanswaay** [comment]
Thanks @JimBacon , I have tested. However I still cannot change the names of the bumblebees and dragonflies.
What I did:

- Created a sample (ID 22926548)
- This included one butterfly (bruin zandoogje), one dragonfly (lantaarntje) and one bumblebee (Bombus terrestris, I can only add scientific names for bumblebees).
- Then I tried to change them. This went smooth for the butterflies.
- For the bumblebees nothing happened, when I started typing a new name (Bombus pratorum) I did not get any suggestions and no name popped up to choose from:
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/d2ec2265-8e12-46a5-96b5-6887f84f63c8)

- For the dragonflies I did get alternative options when trying to change it to 'variabele waterjuffer':
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/12b2bd58-d3d5-4b1e-be21-1f847b55bcb7)

However only options which were no dragonflies, but other species groups, and interestingly no option for the species I wanted to change the name to.

**Comment by JimBacon** [comment]
Hi @chrisvanswaay ,

Thanks very much for checking.

- Sounds like the app needs to update the list of bumblebees as there are 31 Dutch common names on the server. I cannot compare as I don't have a phone to hand.
- For your bumblebee edit, no name was found as that bit in brackets is not a correct match. 
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/9a24ef12-c717-4d54-ad88-15923464a199)
- For the dragonfly edit, that is very strange! I am masquerading as you so should see exactly the same but get
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/a9f39fab-6e33-4922-8c3a-f1e1b0a2a5d5)

SORRY, you are right. When adding a new record, the correct species list is used but, when editing, we are still stuck with the butterfly list each time. I'm investigating.

**Comment by JimBacon** [comment]
Whoops, hit the enter button too soon. Still replying...

**Comment by chrisvanswaay** [comment]
My app should be the last stable beta version, see https://github.com/BiologicalRecordsCentre/ABLE/issues/598 about the issues I had.

**Comment by JimBacon** [comment]
Also needed a fix for submitting records from multiple grids. https://github.com/Indicia-Team/client_helpers/issues/145

**Comment by JimBacon** [comment]
Hi @chrisvanswaay 
I think I have fixed all the issues with editing the different species groups in the 15-minute counts. Would you kindly try it again for me.
I note that the form does not show the attribute listing the species groups that were looked for. Should I raise another issue to add that feature?

**Comment by chrisvanswaay** [comment]
@JimBacon Tested it, and it works! thanks.
Indeed the species groups which have been counted should be added to the reports and downloads. I think @DavidRoy already made an issue for that.

**Comment by JimBacon** [comment]
I can find https://github.com/BiologicalRecordsCentre/ABLE/issues/552. I'll add a note to that issue to include updating the recording form to allow editing of species groups too.
